### PR TITLE
Make the search API tests pass

### PR DESCRIPTION
**Pull request by xcambar**
This PR fixes the tests of the search API. I've chosen this API simply because it's (almost) the smallest test file in the repo.

The point of this PR is to test the HTTP requests built by `node-github`. For this, I used `nock`, a HTTP mocking library.
I would have fixed more tests, but I preferred to gather feedback before doing so.

If you think this is the right way to go (and so do I), then we can start fixing the rest of the test suite and provide this library with the green badge it deserves :smile: .

### CODE REVIEW

**Comment by kaizensoze** [comment]
Only issue with this is it's going to get overwritten when running `node generate.js`. The changes would need to be done in the templates and generation script.

**Comment by xcambar** [comment]
I was secretly hoping to get rid of the generation of tests, because existing tests are already versioned, and adding one test at a time is not that much work.

:confused:

**Comment by kaizensoze** [comment]
It's up to you. Based on my experience going through the entire routes.json file, I'd think it'd be really tedious to manually edit each test. Wouldn't it just be a matter of changing the templates to:

test_section.js.tpl

``` javascript
/*
 * Copyright 2012 Cloud9 IDE, Inc.
 *
 * This product includes software developed by
 * Cloud9 IDE, Inc (http://c9.io).
 *
 * Author: Mike de Boer <info@mikedeboer.nl>
 */

"use strict";

var Assert = require("assert");
var Client = require("./../index");
var nock = require('nock');

describe("[<%sectionName%>]", function() {
    var client;
    var token = "my test token";

    beforeEach(function() {
        client = new Client();
        client.authenticate({
            type: "oauth",
            token: token
        });
    });

<%testBody%>
});
```

test_handler.js.tpl

``` javascript
    it("should successfully execute <%name%>",  function(next) {
        var expected = nock('https://api.github.com')
            .<%method%>(<%name2%>)
            .query({ access_token: token })
            //.<%TODO%>
            .reply();
        client.<%funcName%>(
            <%params%>
        );
        expected.done();
        next();
    });
```

And small change in the generate script:

``` javascript
testSections[section].push(TestHandlerTpl
                    .replace("<%name%>", block.method + " " + block.url + " (" + funcName + ")")
                    .replace("<%method%>", block.method.toLowerCase())
                    .replace("<%name2%>", "'" + block.url + "'")
                    .replace("<%funcName%>", section + "." + funcName)
                    .replace("<%params%>", getParams(block.params, "            "))
                );
```

And then the remaining part would be that <%TODO%> tag and replacing the param types with valid values.

Would the nock stuff need to significantly vary on a per test basis?

**Comment by xcambar** [comment]
Some food for thoughts:
- Current params in the generated tests are wrong (_ie_,not realistic), hence that would require a "test_params" section in `routes.json` for correctness.
- It only allows a fixed number of tests (currently 1) per method. Consequently, you can not test validators.
- You can not update one test without risking to break the others.
  The `nock` part of the tests may not vary a lot, which allows for factorisation, but

The first point needs to a lot of refactoring in `routes.json` anyway. So a big amount of work **is** required if the tests are meant to be useful.

What do you think?

**Comment by kaizensoze** [comment]
By not realistic do you mean that it's currently [incorrectly] outputting the param types? Instead it would need to output a value based on the param's type and validation field, but the refactor would be mostly isolated to the generate script. Routes.json might need a _little_ tweaking.

Ex:

``` javascript
"role": {
    "type": "String",
    "required": true,
    "validation": "^(admin|member)$",
    "invalidmsg": "admin, member",
    "description": "The role to give the user in the organization."
}
```

The generate script would parse the validation field and pick the first option, outputting 'admin'.

As for possible changes needed in the routes.json, two things:
- I'm not entirely sure if the param validation field is currently standardized. It'd require going through routes.json and making sure everything is of the format ^(x|y)$
- Right now, the default value for a param is included in the invalidmsg:

``` javascript
"filter": {
    "type": "String",
    "required": false,
    "validation": "^(all|2fa_disabled)$",
    "invalidmsg": "all, 2fa_disabled, default: all",
    "description": "Filter members returned in the list."
},
```

Ideally you'd want to move the default value to a separate field to parse it more easily, but it's not required for the refactor since you're just going to pick the first allowed value anyway. Might be helpful though to pick the default value to go with the most common use case for the test.

I agree on the third point though, it would be one of those pain in the ass all-or-nothing refactors.
It's tedious, but not as tedious as creating all of the tests manually.

**Comment by xcambar** [comment]
I wish I could agree with your proposal/roadmap, but it is unfortunately not the case. Too many road bumps ahead, as far as I can tell.

Now that you have everything in hand to make the tests run (with #77), I will leave it up to you to implement them as you see fit.
Thank you though for forking and maintaining over the initial project, it has been immensely useful to me.

**Comment by kaizensoze** [comment]
Alright, fair enough. I'll take a look at it when I get a chance, but thanks for the PR!

**Pull request closed without merging**
